version: '3.7'

networks:
  cqu-g4-net:
    driver: bridge
services:
  discovery-server:
    container_name: discovery-server
    image: ghcr.io/cqu-g4/discovery-server:main
    ports:
      - 8761:8761
    networks:
      - cqu-g4-net
  configuration-server:
    container_name: configuration-server
    image: ghcr.io/cqu-g4/configuration-server:main
    volumes:
      - ./configuration-repo:/app/configuration-repo
    ports:
      - 8888:8888
    networks:
      - cqu-g4-net
    depends_on:
      - discovery-server
  gateway-server:
    container_name: gateway-server
    image: ghcr.io/cqu-g4/gateway-server:main
    ports:
      - 8000:8000
    networks:
      - cqu-g4-net
    depends_on:
      - discovery-server
      - configuration-server
  admin-service:
    container_name: admin-service
    image: ghcr.io/cqu-g4/admin-service:main
    ports:
      - 8081:8081
    volumes:
      - ./configuration-repo:/app/conf/
    networks:
      - cqu-g4-net
    depends_on:
      - discovery-server
      - configuration-server
  user-service:
    container_name: user-service
    image: ghcr.io/cqu-g4/user-service:main
    volumes:
      - ./configuration-repo:/app/conf/
    ports:
      - 8083:8083
    networks:
      - cqu-g4-net
    depends_on:
      - discovery-server
      - configuration-server
  auth-service:
    container_name: auth-service
    image: ghcr.io/cqu-g4/auth-service:main
    ports:
      - 7090:7090
    networks:
      - cqu-g4-net
    depends_on:
      - discovery-server
      - configuration-server
  therapy-provider-service:
    container_name: therapy-provider-service
    image: ghcr.io/cqu-g4/therapy-provider-service:main
    ports:
      - 8082:8082
    networks:
      - cqu-g4-net
    depends_on:
      - discovery-server
      - configuration-server
