version: '3.8'

networks:
  mongodb:
    driver: bridge

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodb_database_data:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_USERNAME=rooot
      - MONGODB_ROOT_PASSWORD=aASDFGHWERTYUIOVBNMBNXCVB234567SDFGHJ
    networks:
      - mongodb
    ports:
      - '27017:27017'
  mongoexpress:
    image: mongo-express
    ports:
      - "9090:8081"
    networks:
      - mongodb
    environment: 
      # - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
      # - MONGOEXPRESS_LOGIN=admin
      # - MONGOEXPRESS_PASSWORD=GnusmaS@321
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=rooot
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=aASDFGHWERTYUIOVBNMBNXCVB234567SDFGHJ
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=GnusmaS@321
    depends_on:
      - mongodb
    restart: unless-stopped
volumes:
  mongodb_database_data:
    driver: local