version: '3.8'

networks:
  mongodb:
    driver: bridge

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodb_database_data:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_USERNAME=rooot
      - MONGODB_ROOT_PASSWORD=aASDFGHWERTYUIOVBNMBNXCVB234567SDFGHJ
    networks:
      - mongodb
    ports:
      - '27017:27017'
  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    environment: 
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    restart: always
volumes:
  mongodb_database_data:
    driver: local